CXX=g++
CXXFLAGS=-std=c++11

# HEADERS=utils.h intrin-wrapper.h

val_test01_solved: val_test01_solved.cpp
	$(CXX) $(CXXFLAGS) val_test01_solved.cpp -o val_test01_solved

val_test02_solved: val_test02_solved.cpp
	$(CXX) $(CXXFLAGS) val_test02_solved.cpp -o val_test02_solved

# %.o: %.cpp $(HEADERS)
# 	$(CXX) -c $(CXXFLAGS) $(INC) $< -o $@
#
# # MMult1: MMult1.o
# # 	$(CXX) $(CXXFLAGS) MMult1.o -o MMult1
#
# val_test01_solved: val_test01_solved.o
# 	$(CXX) $(CXXFLAGS) val_test01_solved.o -o val_test01_solved
#
# clean:
# 	rm *.o
